<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="ws"
           targetNamespace="ws" elementFormDefault="qualified">

    <!--User-->
    <xs:complexType name="user">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="e-mail" type="xs:string"/>
            <xs:element name="first-name" type="xs:string"/>
            <xs:element name="last-name" type="xs:string"/>
        </xs:sequence>
        <xs:attribute default="false" name="activated"/>
    </xs:complexType>

    <xs:element name="UserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="username" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="User" type="tns:user"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Agent-->
    <xs:complexType name="agent">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="first_Name" type="xs:string"/>
            <xs:element name="last_Name" type="xs:string"/>
            <xs:element name="business-ID" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="AgentRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="username" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AgentResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Agent" type="tns:agent"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Accomodation-->
    <xs:complexType name="accomodation-type">
        <xs:sequence>
            <xs:element name="type-ID" type="xs:int"/>
            <xs:element name="type-name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="accomodation-service">
        <xs:sequence>
            <xs:element name="service-ID" type="xs:int"/>
            <xs:element name="service-name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="category">
        <xs:sequence>
            <xs:element name="category-ID" type="xs:int"/>
            <xs:element name="category-name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TLocation">
        <xs:sequence>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPrice">
        <xs:sequence>
            <xs:element name="value" type="xs:float"/>
            <xs:element name="start-date" type="xs:date"/>
            <xs:element name="end-date" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="accomodation">
        <xs:sequence>
            <xs:element name="agent" type="tns:agent"/>
            <xs:element name="location" type="tns:TLocation"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="max-persons">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                        <xs:pattern value="[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="category" type="tns:category"/>
            <xs:element name="accomodation-type" type="tns:accomodation-type"/>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="picture" type="xs:base64Binary"/>
            </xs:sequence>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="accomodation-service" type="tns:accomodation-service"/>
            </xs:sequence>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" name="price"
                            type="tns:TPrice"/>
            </xs:sequence>
            <xs:element name="accommodation-id" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="CreateAccommodationRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Accommodation" type="tns:accomodation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateAccommodationResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Accommodation" type="tns:accomodation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AccommodationRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AccommodationResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Accommodation" type="tns:accomodation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Message-->
    <xs:complexType name="message">
        <xs:sequence>
            <xs:element name="agent" type="tns:agent"/>
            <xs:element name="content" type="xs:string"/>
            <xs:element name="user" type="tns:user"/>
            <xs:element name="message-id" type="xs:int"/>
        </xs:sequence>
        <xs:attribute default="false" name="read" type="xs:boolean"/>
    </xs:complexType>

    <xs:element name="MessageRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message-id" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="MessageResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Message" type="tns:message"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Reservation-->
    <xs:complexType name="reservation">
        <xs:sequence>
            <xs:element name="user" type="tns:user"/>
            <xs:element name="accomodation" type="tns:accomodation"/>
            <xs:element name="reservation-id" type="xs:int"/>
        </xs:sequence>
        <xs:attribute default="false" name="realized" type="xs:boolean"/>
        <xs:attribute default="true" name="active" type="xs:boolean"/> <!--not canceled-->
        <xs:attribute name="num-persons">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="final-price" type="xs:float"/>
        <xs:attribute name="start-date" type="xs:date"/>
        <xs:attribute name="end-date" type="xs:date"/>
    </xs:complexType>

    <xs:element name="ReservationRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reservation-id" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ReservationResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Reservation" type="tns:reservation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Review-->
    <xs:complexType name="review">
        <xs:sequence>
            <xs:element name="grade" type="xs:int"/>
            <xs:element name="accomodation" type="tns:accomodation"/>
            <xs:element name="user" type="tns:user"/>
            <xs:element name="comment" type="xs:string"/>
            <xs:element name="review-id" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="allowed" type="xs:boolean"/>
    </xs:complexType>

    <xs:element name="ReviewRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="review-id" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ReviewResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Review" type="tns:review"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>