//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:45:01 AM CEST 
//


package com.ftn.xml.agent.domain;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}agent"/>
 *         &lt;element name="location" type="{}TLocation"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="max-persons">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;pattern value="[0-9]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}category"/>
 *         &lt;element ref="{}accomodation-type"/>
 *         &lt;sequence>
 *           &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}accomodation-service"/>
 *         &lt;/sequence>
 *         &lt;sequence>
*            &lt;element name="price" type="{}TPrice" maxOccurs="unbounded"/>
 *         &lt;/element>
 *         &lt;element name="accommodation-id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agent",
    "location",
    "name",
    "description",
    "maxPersons",
    "category",
    "accomodationType",
    "picture",
    "accomodationServices",
    "prices",
    "accommodationId"
})
@Entity
@XmlRootElement(name = "accomodation")
public class Accomodation {

    @ManyToOne
    @XmlElement(required = true)
    protected Agent agent;
    @XmlElement(required = true)
    @ManyToOne
    protected TLocation location;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "max-persons")
    protected int maxPersons;
    @XmlElement(required = true)
    @ManyToOne
    protected Category category;
    @XmlElement(name = "accomodation-type", required = true)
    @ManyToOne
    protected AccomodationType accomodationType;
    @XmlElement(required = true)
    @Lob
    protected String pictures;
    @XmlElement(name = "accomodation-service", required = true)
    @ManyToMany
    @JoinTable(
            name="accommodation_accomservice",
            joinColumns = @JoinColumn(
                    name="accommodationId"),
            inverseJoinColumns = @JoinColumn(
                    name="serviceId"
            )
    )
    protected List<AccomodationService> accomodationServices;
    @XmlElement(name = "price-plan", required = true)
    @OneToMany
    protected List<TPrice> prices;
    @Id
    @XmlElement(name = "accommodation-id")
    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    protected int accommodationId;

    @OneToMany
    protected List<Image> images;

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link TLocation }
     *     
     */
    public TLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLocation }
     *     
     */
    public void setLocation(TLocation value) {
        this.location = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the maxPersons property.
     * 
     */
    public int getMaxPersons() {
        return maxPersons;
    }

    /**
     * Sets the value of the maxPersons property.
     * 
     */
    public void setMaxPersons(int value) {
        this.maxPersons = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the accomodationType property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationType }
     *     
     */
    public AccomodationType getAccomodationType() {
        return accomodationType;
    }

    /**
     * Sets the value of the accomodationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationType }
     *     
     */
    public void setAccomodationType(AccomodationType value) {
        this.accomodationType = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the picture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPicture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * byte[]
     * 
     */
    public void setPictures(String pictures) {
        this.pictures = pictures;
    }
    public String getPictures() {
        return this.pictures;
    }

    /**
     * Gets the value of the accomodationService property.
     * 
     * @return
     *     possible object is
     *     {@link AccomodationService }
     *     
     */
    public List<AccomodationService> getAccomodationServices() {
        return accomodationServices;
    }

    /**
     * Sets the value of the accomodationService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccomodationService }
     *     
     */
    public void setAccomodationService(List<AccomodationService> value) {
        this.accomodationServices = value;
    }

    /**
     * Gets the value of the pricePlan property.
     * 
     * @return
     *     possible object is
     *     {@link TPrice }
     *     
     */
    public List<TPrice> getPrices() {
        return prices;
    }

    /**
     * Sets the value of the pricePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrice }
     *     
     */
    public void setPrices(List<TPrice> value) {
        this.prices = value;
    }

    /**
     * Gets the value of the accommodationId property.
     * 
     */
    public int getAccommodationId() {
        return accommodationId;
    }

    /**
     * Sets the value of the accommodationId property.
     * 
     */
    public void setAccommodationId(int value) {
        this.accommodationId = value;
    }

    public List<Image> getImages() {
        return images;
    }

    public void setImages(List<Image> images) {
        this.images = images;
    }

    @Override
    public String toString() {
        return "Accomodation{" +
                "agent=" + agent +
                ", location=" + location +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", maxPersons=" + maxPersons +
                ", category=" + category +
                ", accomodationType=" + accomodationType +
                ", pictures=" + pictures +
                ", accomodationServices=" + accomodationServices +
                ", prices=" + prices +
                ", accommodationId=" + accommodationId +
                '}';
    }
}
